baseURL = 'https://chippewavalleycodecamp.com/'
languageCode = 'en-us'
title = 'Chippewa Valley Code Camp'

theme='codeCamp'

sectionPagesMenu = 'main'

[[menus.topNav]]
name = 'Sessions'
pageRef = '/Sessions'
weight = 11

[[menus.topNav]]
name = 'Speakers'
pageRef = '/Speakers'
weight = 12

[[menus.topNav]]
name = 'Register'
pageRef = 'https://www.eventbrite.com/e/chippewa-valley-code-camp-2025-tickets-1128422765869'
weight = 13

[[menus.topNav]]
name = 'Schedule'
pageRef = '/Schedule'
weight = 14

[[menus.topNav]]
name = 'Sponsors'
pageRef = '/Sponsors'
weight = 15

[[menus.topNav]]
name = 'Past Camps'
pageRef = '/past_camps'
weight = 16

[[menus.topNav]]
name = 'Promo Kit'
pageRef = '/promo_kit'
weight = 17


[[menus.footer]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

[params]
  # Site-wide announcement banner (appears on all pages unless hideAnnouncement = true in page front matter)
  announcement = '2026 Registration is Now Open!'
  announcementLink = 'https://www.eventbrite.com/e/chippewa-valley-code-camp-2026-tickets-1980783904981'
  announcementButtonText = 'Register on Eventbrite'
  announcementConfetti = true  # Set to false to disable confetti animation